name=input("enter your name: ")
branch=input("enter your branch: ")
gender=input("enter your Gender: ")
college=input("enter your College Name: ")
age=int(input("enter your age: "))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",college)
print("age:",age)
