player1=int(input("enter the run of player 1: "))
player2=int(input("enter the run of player 2: "))
player3=int(input("enter the run of player 3: "))
print("Strike rate of player 1 is: ",player1*100/60)
print("Strike rate of player 2 is: ",player2*100/60)
print("Strike rate of player 3 is: ",player3*100/60)
print("if player 1 plays 60 more balls then his score will be : ",player1*2)
print("if player 2 plays 60 more balls then his score will be : ",player2*2)
print("if player 3 plays 60 more balls then his score will be : ",player3*2)
print("maximum sixes of player 1 could be : ",player1//6)
print("maximum sixes of player 2 could be : ",player2//6)
print("maximum sixes of player 3 could be : ",player3//6)
